#  GitHub Actions 工作流程配置文件，用于在代码仓库发生特定事件时自动执行任务
name: Run Java Git Diff By Local

# 在 push 事件（代码推送）或 pull_request 事件（创建/更新PR）触发时，自动执行jobs操作
on:
  push:
    branches:
      - master-close
  pull_request:
    branches:
      - master-close

#
jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 2  # 检出最后两个提交，以便可以比较 HEAD~1 和 HEAD

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'  # 你可以选择其他发行版，如 'adopt' 或 'zulu'
          java-version: '11'

      - name: Run Java code
        run: |
          cd openai-code-review-sdk/src/main/java
          javac com/zhihao/sdk/OpenAiCodeReview.java
          java com.zhihao.sdk.OpenAiCodeReview
